### ISSUE TITLE
Enable GitHub SSO on premise

### ISSUE THREAD

**Issue by hpurmann** [getsentry/sentry-auth-github#22]
Hey!

I want to enable the GitHub SSO on my onpremise Docker-based installation of sentry. I couldn't make it work so far.

I added a new application to our GitHub organization. I'm passing `GITHUB_APP_ID` and `GITHUB_API_SECRET` to the containers with the `docker-compose.yml`.

I logged into the running worker container with `docker-compose exec worker bash` and executed the install
```
pip install https://github.com/getsentry/sentry-auth-github/archive/master.zip
```
Afterwards, I ran `sentry upgrade`.
I logged out, re-build the containers and nothing changed. I expected to see an item under `http://<sentry-url>/settings/<org>/auth/`

Is this repository still maintained? I also found that `sentry-plugins` supports a GitHub plugin but that seems to only link the repository? Is that correct?

Greetings
Hendrik

**Comment by dcramer** [comment]
Yes this repo is maintained and used on Sentry.io. You need to install the dep in your container and afaik rebuilding a container would uninstall it unless you pinned it. Either way I’m closing this issue as it’s a usage question and not a but. 

https://sentry.io/support.

**Comment by hpurmann** [comment]
Ok for anyone finding this: I managed to install this plugin inside of Docker by [reading the docs about requirements.txt](https://pip.pypa.io/en/stable/reference/pip_install/#git) and then adding the repository URL to the `requirements.txt` like so:
```
# Add plugins here
git+https://github.com/getsentry/sentry-auth-github.git@master#egg=sentry-auth-github
```

**Comment by viktorsmari** [comment]
@hpurmann could you write a short blog post about it and link to it or update the issue? 
What did you do after adding this to the file?
This issue is a top hit on Google for 'sentry onpremis github sso'

**Comment by 18308996929** [comment]
how to install plugin from source   on my onpremise Docker-based installation of sentry?
I try these, but not work:
   python setup.py  install 
 
Greetings
